# ===================================================================
# CONFIGURATION GÉNÉRALE DE L'APPLICATION
# ===================================================================
spring.application.name=scoring

# Port sur lequel le backend va s'exécuter (8080 par défaut)
server.port=8080

# ===================================================================
# CONFIGURATION DE LA BASE DE DONNÉES (POSTGRESQL)
# ===================================================================
# URL de connexion : localhost (ta machine) / port 5432 (port par défaut de Postgres) / nom de ta BDD
spring.datasource.url=jdbc:postgresql://localhost:5432/scoring
spring.datasource.username=postgres
spring.datasource.password=louz

# Le pilote JDBC pour PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURATION JPA / HIBERNATE
# ===================================================================
# Le dialecte indique à Hibernate comment générer du SQL spécifique à PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto=update : Crée ou met à jour les tables automatiquement en fonction de tes entités Java (comme la classe Task)
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL générées par Hibernate dans la console (très utile pour le débogage)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true